version: "3.8"

networks:
  prod:
     external: true  

#volumes:
  #code:

services:
  frontend:
    image: ${IMAGE_BASE}/stable/frontend:${FRONTEND_RELEASE_TAG}
    environment:
      - TZ=Europe/Paris
    #volumes:
    #    - /etc/localtime:/etc/localtime:ro
    #   - code:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    links:
      - api
    container_name: frontend
    depends_on:
      - api
    labels:
        - traefik.enable=true
        - traefik.http.routers.api-release.rule=Host(`${DOMAIN_BASE}`)
        - traefik.http.routers.api-release.entrypoints=websecure
        - traefik.http.services.api-release.loadbalancer.server.port=3000
    networks:
      - prod