version: "3.8"

networks:
  preprod:
     external: true  

services:
  frontend-release:
    image: ${IMAGE_BASE}/release/frontend:${FRONTEND_RELEASE_TAG}
    container_name: frontend-release
    hostname: dev.dsp-archiwebo21-ct-df-an-cd.fr
    extra_hosts:
      - "api.dev.dsp-archiwebo21-ct-df-an-cd.fr:45.155.170.65" 
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
    volumes:
       - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - api-release
    labels:
        - traefik.enable=true
        - traefik.http.routers.frontend-release.rule=Host(`dev.${DOMAIN_BASE}`)
        - traefik.http.routers.frontend-release.entrypoints=websecure
        - traefik.http.services.frontend-release.loadbalancer.server.port=3000
    networks:
      - preprod