version: "3.8"

networks:
<<<<<<< HEAD
<<<<<<< HEAD
  preprod:
     external: true  

#volumes:
#  code: 

services:
  frontend:
    image: ${IMAGE_BASE}/release/frontend:${FRONTEND_RELEASE_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
      - API_BASE_URL=http://api-release:3000
    volumes:
       - /etc/localtime:/etc/localtime:ro
    #   - code:/my-project:rw
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    links:
     - api-release:api
    container_name: frontend-release
=======
  prod:
=======
  preprod:
>>>>>>> 8aea497 (Update docker compose file for differents envs)
     external: true  

#volumes:
  #code:

services:
  front-release:
    image: ${IMAGE_BASE}/release/frontend:${FRONTEND_RELEASE_TAG}
    environment:
      - TZ=Europe/Paris
    #volumes:
    #    - /etc/localtime:/etc/localtime:ro
    #   - code:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    links:
<<<<<<< HEAD
      - api
    container_name: frontend
>>>>>>> 34a778e (Set up infra as code)
=======
      - api-release:api
    container_name: frontend-release
>>>>>>> 8aea497 (Update docker compose file for differents envs)
    depends_on:
      - api
    labels:
        - traefik.enable=true
<<<<<<< HEAD
<<<<<<< HEAD
        - traefik.http.routers.frontend-release.rule=Host(`dev.${DOMAIN_BASE}`)
        - traefik.http.routers.frontend-release.entrypoints=websecure
        - traefik.http.services.frontend-release.loadbalancer.server.port=3000
    networks:
      - preprod
=======
        - traefik.http.routers.api-release.rule=Host(`${DOMAIN_BASE}`)
        - traefik.http.routers.api-release.entrypoints=websecure
        - traefik.http.services.api-release.loadbalancer.server.port=3000
    networks:
      - prod
>>>>>>> 34a778e (Set up infra as code)
=======
        - traefik.http.routers.api-release.rule=Host(`dev.${DOMAIN_BASE}`)
        - traefik.http.routers.api-release.entrypoints=websecure
        - traefik.http.services.api-release.loadbalancer.server.port=3000
    networks:
      - preprod
>>>>>>> 8aea497 (Update docker compose file for differents envs)
