version: "3.8"

networks:
  preprod:
     external: true  

#volumes:
#  code: 

services:
  frontend:
    image: ${IMAGE_BASE}/release/frontend:${FRONTEND_RELEASE_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
      - NEXT_PUBLIC_BASE_URL=http://api-release:3000
      - NEXT_PUBLIC_GOOGLE_ANALYTICS = "G-20KRPHLP3Z"
      - NEXT_PUBLIC_GOOGLE_TAGMANAGER = "GTM-KMZCFTF"
      - SITE_URL = "https://dev.dsp-archiwebo21-ct-df-an-cd.fr/"

    volumes:
       - /etc/localtime:/etc/localtime:ro
    #   - code:/my-project:rw
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    links:
     - api-release:api
    container_name: frontend-release
    depends_on:
      - api
    labels:
        - traefik.enable=true
        - traefik.http.routers.frontend-release.rule=Host(`dev.${DOMAIN_BASE}`)
        - traefik.http.routers.frontend-release.entrypoints=websecure
        - traefik.http.services.frontend-release.loadbalancer.server.port=3000
    networks:
      - preprod