import React from "react";
import Head from "next/head";
import Header from "../../../component/Header";
import Footer from "../../../component/Footer";

import Breadcrumbs from 'nextjs-breadcrumbs';



export default function grandtirage() {


  return (
    <div className="main2">
      <Head>
        <title>Grand tirage au sort - Jeux concours</title>
        <meta name="Earl Grey Bio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section
        className="block"
        style={{ borderBottom: "solid 1px white" }}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            width: "100%",
            padding: 25,
            background:"linear-gradient(48deg, rgba(56,135,13,1) 0%, rgba(56,135,13,1) 28%, rgba(144,203,6,1) 100%, rgba(211,255,0,1) 100%)",
      
          }} >
          
   
              <h1 style={{color:"white",fontSize:35}}>Résultat du grand tirage au sort !</h1>
                <Breadcrumbs useDefaultStyle={false} containerClassName="breakLight"rootLabel="Accueil" />
        </div>

     
      </section>
      <Footer />
    </div>
  );
}
