import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../component/Header";
import Footer from "../../component/Footer";
import { useRouter } from "next/router";
import tea1 from "../../image/tea1.png";
import tea2 from "../../image/tea2.png";
import tea3 from "../../image/tea3.png";
import tea4 from "../../image/tea4.png";
import tea5 from "../../image/tea5.png";
import Link from "next/link";
import "animate.css";


export default function lots() {

    const gift = [
        {
          name: "Coffret 32 euros",
          src: tea2,
          descrition:"L’infusion au pamplemousse, produit détoxifiant, apporte de nombreux bienfaits pour la santé ",
          href:"/coffret32"
        },
        {
          name: "Coffret 69 euros",
          src: tea1,
          descrition:"Thé matcha pour maigrir ? En tout cas il est nécessaire de l’accompagner avec un régime alimentaire .",
          href:"/coffret69"
        },
        {
          name: "100g thé signature",
          src: tea3,
          descrition:"Nous vous proposons un coffret de thés à personnaliser. Cette boîte sera composé de 6 de nos thés en miniature.",
          href:"/thesignature"
        },
        {
          name: "Infuseur à thé",
          src: tea4,
          descrition:"L’infusion au pamplemousse, produit détoxifiant, apporte de nombreux bienfaits pour la santé",
          href:"/infuseur "
        },
        {
          name: "100g thé detox ",
          src: tea5,
          descrition:"Ce thé a de nombreuses vertus pour la santé et un goût très prononcé. Le thé Matcha est un thé vert japonais en poudre",
          href:"/thedetox"
        },
      ];
    


  return (
    <div className={styles.main2}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header menu="lots"/>
      <section style={{display:"flex",justifyContent:"center"}}>
      <div  style={{ paddingTop: 125,
      display:"flex",
      width:"100%",
      flexWrap:"wrap",
      maxWidth:960,
      paddingBottom: 50,
        minHeight:"100vh" }}>
        {gift.map((g,i) => (
          <div key={i} className="lotsItems animate_animated animate__bounceInLeft " style= { i/2 == Math.round(i/2) ?stylez.dark :stylez.light }>
             <Image  src={g.src} alt={g.name}/>
             <div style={{display:"flex",flexDirection:"column",}}>
                <h3>{g.name}</h3>
                <p>{g.descrition}</p>
                <Link href={`lots${g.href}`}>En savoir plus</Link>    
             </div> 
          </div>
            ))}
        </div>
      </section>
      <Footer />
    </div>
  );
}
const stylez ={

    dark :{
      background:"#38870D"
    },

    light:{
        background:"white",
        color :"#38870D"
    }
}