import { NextPage } from "next"
import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/Header'

const Accueil: NextPage = () => {
  return(
    <>
      <Head>
        <title>Thé Bingo | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="container">
        
      </div>
    </>
  )
}

export default Accueil