import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import tea1 from "../image/tea1.png";
import styles from "../styles/Home.module.css";
import logo from "../image/whitelogo.png";
import Header from "../component/Header";
import Footer from "../component/Footer";
import { useRouter } from "next/router";
import arrow from "../image/arrow.gif";
import Link from "next/link";



export default function coffret32() {


  return (
    <div className={styles.main2}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section style={{ paddingTop: 125, paddingBottom: 50,minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center" }}>
        <h1>Coffret 32 euros</h1>
        <div>
         <Image src={tea1} alt="coffret tea" />
        </div>
        <div style={{maxWidth:500}}>
          <h2 style={{textAlign:"center"}}>Description : INFUSION AU PAMPLEMOUSSE </h2>
          <p style={{padding:10}} > 
          Ceci est un lot de notre <span style={{color:"green",fontWeight:"bold"}} ><Link href="/"> jeu concour </Link></span> <br></br>
          L’infusion au pamplemousse est bien la boisson idéale avant d’aller se coucher. Cette boisson vous permet d’allier la gourmandise avec une santé de fer!

Cette tisane, tout comme de nombreux thés, a le mérite d’apporter beaucoup de bénéfices pour la santé. Les avantages de consommer de la tisane ou une infusion comprennent la détente du corps, le refroidissement de la température corporelle, l’assouplissement de l’estomac et la réduction de la rétention d’eau dans le corps.

De plus, suivant son goût et les ingrédients qui le compose, les bénéfices peuvent être plus importants.

L’infusion au pamplemousse, produit détoxifiant, apporte de nombreux bienfaits pour la santé :

Riche source de vitamines et de minéraux, contient une quantité faible de calories,
Une activité antioxydante élevée
Aide pour la perte de poids ou son maintien,
Boost le système immunitaire grâce aux bioflavonoïdes qui le composent,
Combat le diabète grâce à sa haute teneur en Vitamines C,
Allié contre de nombreuses maladies, tel que des brulures d’estomac, calcul rénaux, cancers, cholestérol
Et pour finir, cette boisson sera la boisson à préférer pour les femmes enceintes!
          </p>

        </div>
          <section className="childLot">
              <p>Voir les autres lots</p>
              <Link href="/coffret32">Coffret 39 euros</Link>
              <Link href="/coffret69">Coffret 69 euros</Link>
              <Link href="/thesignature">100g thé signature</Link>
              <Link href="/thedetox">100g thé détox</Link>
              <Link href="/infuseur">Infuseur à thé</Link>
          </section>
      </section>
      <Footer />
    </div>
  );
}
