import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import tea2 from "../image/tea2.png";
import styles from "../styles/Home.module.css";
import logo from "../image/whitelogo.png";
import Header from "../component/Header";
import Footer from "../component/Footer";
import { useRouter } from "next/router";
import Link from "next/link";
import arrow from "../image/arrow.gif";



export default function coffret69() {


  return (
    <div className={styles.main2}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section style={{ paddingTop: 125, paddingBottom: 50,height:"100vh" }}>
       <div>
        <h1></h1>
         <Image src={tea2} alt=""/>
       </div>
             <div className="childLot">
              <p>Voir les autres lots</p>
              <Link href="/coffret32">Coffret 39 euros</Link>
              <Link href="/coffret69">Coffret 69 euros</Link>
              <Link href="/thesignature">100g thé signature</Link>
              <Link href="/thedetox">100g thé détox</Link>
              <Link href="/infuseur">Infuseur à thé</Link>
          </div>
      </section>
      <Footer />
    </div>
  );
}
