import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"

export default function Conditions() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Conditions générales de vente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className={styles.part}>
        <h1 className={styles.h1}>Conditions générales de vente</h1>
<<<<<<< HEAD
        <p>
        POLITIQUE DE CONFIDENTIALITE DES DONNEES DU SITE 

PREAMBULE
formisunion.com s’engage à ce que la collecte et le traitement de vos données soient effectués de manière licite, loyale et transparente, conformément au règlement général sur la protection des données (RGPD) et à la Loi informatiques et Libertés de 1978 modifiée.
La collecte des données à caractère personnel de ses prospects et clients se limite au strict nécessaire, conformément au principe de minimisation des données, et indique quelles sont les finalités poursuivies par le recueil de ces données, si fournir ces données revêt un caractère facultatif ou obligatoire pour gérer les demandes et qui pourra en prendre connaissance.
&nbsp;
ARTICLE 1 DEFINITIONS <br></br>
&nbsp;
L’Éditeur : La personne, physique ou morale, qui édite les services de communication au public en ligne, c’est-à-dire : Médecine Roumanie Académie


Le site :  www.formisunion.com .  L’ensemble du (des) site(s), pages Internet et service(s) en ligne proposés par l’Éditeur, qui exploite le(s) site(s) accessible(s )à partir de(s) (l’) adresse(s) URL suivante(s) :
– formisunion.com
&nbsp;
L’Utilisateur : La personne utilisant le Site et les services. <br></br>
&nbsp;
ARTICLE 2 NATURE DES DONNEES COLLECTEES

Dans le cadre de l’utilisation des Sites, pour fournir un service de formation en ligne, l’Éditeur est susceptible de collecter les catégories de données suivantes concernant ses Utilisateurs :
Données d’état-civil, d’identité, d’identification (nom, prénom, mail, date de naissance, profession, numéro de téléphone…)
Données relatives à la vie personnelle (habitudes de vie, situation familiale, hors données sensibles ou dangereuses)
Données relatives à la vie professionnelle (CV, scolarité, formation professionnelle, distinctions…)
Informations d’ordre économique et financier (revenus, situation financière, situation fiscale…)
Données de connexion (adresses IP, journaux d’événements…)
Données de localisation (déplacements, données GPS, GSM…)
L’Editeur s’engage à tenir par écrit un registre de toutes les catégories d’activités de traitement effectuées en tant que responsable de traitement des données susvisées.

ARTICLE 3 INFORMATION ET DROITS DES UTILISATEURS

Par la présente, l’Editeur vous informe clairement sur les traitements de données à caractère personnel qu’il met en œuvre dans le cadre de son activité, comment les données sont collectées, utilisées et protégées.
Tout Utilisateur dispose du droit de demander au responsable de traitement, c’est-à-dire à l’Editeur :
– L’accès aux données à caractère personnel fournies ;
– La rectification ou l’effacement de celles-ci ;
– Une limitation du traitement relatif à sa personne ;
– De s’opposer au traitement ;
– A la portabilité des données ;


ARTICLE 4 SOUS-TRAITANCE

L’Editeur s’engage à ce que tout sous-traitant présente des garanties contractuelles suffisantes quant à la mise en œuvre de mesure techniques et organisationnelles appropriées, afin que le traitement réponse aux exigences du règlement européen sur la protection des données.
L’Editeur pourra faire appel à un ou plusieurs sous-traitant(s) pour mener des activités de traitement spécifiques qui seront soumis aux conditions de la présente Politique. Tout sous-traitant ne sera pas autorisé à faire lui-même appel à un sous-traitant sans l’autorisation écrite préalable de l’Editeur.

ARTICLE 5 COMMUNICATION DES DONNEES PERSONNELLES A DES TIERS

Communication aux autorités sur la base des obligations légales
Sur la base des obligations légales, vos données personnelles pourront être divulguées en application d’une loi, d’un règlement ou en vertu d’une décision d’une autorité réglementaire ou judiciaire compétente.
De manière générale, nous nous engageons à nous conformer à toutes les règles légales qui pourraient empêcher, limiter ou réglementer la diffusion d’informations ou de données et notamment à se conformer à la Loi n° 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés et au Règlement général sur la protection des données (RGPD) de l’Union européenne.


Communication à des tiers en fonction des paramètres du compte
Vos données personnelles sont strictement confidentielles et ne peuvent être divulguées à des tiers, sauf en cas d’accord exprès obtenu via les paramètres de votre compte.
Communication à des tiers pour sollicitation commerciale pour des produits et services équivalents 

Si vous avez effectué une inscription sur notre Site, nous pouvons, avec nos partenaires et de manière occasionnelle, vous tenir informé de nos nouveaux services, actualités et offres spéciales, par courriel, par courrier postal et par téléphone quant à des produits ou services similaires aux produits ou services qui ont fait l’objet de votre intérêt.

Communication à des tiers sous forme agrégée et anonymisée 

Vos données personnelles pourront être utilisées pour enrichir nos bases de données. Elles pourront être transmises à des tiers après avoir été anonymisées et exclusivement à des fins statistiques.

Communication à des tiers partenaires

Nous pouvons mettre certaines données personnelles à la disposition de partenaires stratégiques travaillant avec nous, pour la fourniture de produits et services ou nous aidant à étendre nos services auprès de potentiels partenaires.

Communication à des tiers avec restrictions liées aux destinataires 

Les données personnelles que vous nous communiquez lors de votre inscription sont transmises à nos fournisseurs et filiales pour le traitement de celle-ci. Ces informations sont considérées par nos fournisseurs et filiales comme étant strictement confidentielles.

Communication à des tiers pour marketing direct 

Nous pouvons partager des informations avec des partenaires publicitaires afin de vous envoyer des communications promotionnelles, ou pour vous montrer plus de contenu sur mesure, y compris de la publicité pertinente pour les produits et services susceptibles de vous intéresser, et pour comprendre comment les utilisateurs interagissent avec les publicités.

Engagement sur l’applicabilité de la politique de confidentialité

En cas de communication de vos données personnelles à un tiers, l’Editeur s’assurera que ce dernier est tenu d’appliquer des conditions de confidentialité identiques à celle du Site.


ARTICLE 6 AGREGATION DES DONNEES

Agrégation avec des données non personnelles
Nous pouvons publier, divulguer et utiliser les informations agrégées (informations relatives à tous nos Utilisateurs ou à des groupes ou catégories spécifiques d’Utilisateurs que nous combinons de manière à ce qu’un Utilisateur individuel ne puisse plus être identifié ou mentionné) et les informations non personnelles à des fins d’analyse du secteur et du marché, de profilage démographique, à des fins promotionnelles et publicitaires et à d’autres fins professionnels.
Agrégation avec des données personnelles disponibles sur les comptes sociaux de l’Utilisateur.
Si vous connectez votre compte à un compte d’un autre service afin de faire des envois croisés, ledit service pourra nous communiquer vos informations de profil, de connexion, ainsi que toute autre information dont vous avez autorisé la divulgation. Nous pouvons agréger les informations relatives à tous nos autres Utilisateurs, groupes, comptes, aux données personnelles disponibles sur l’Utilisateur.

ARTICLE 7 COLLECTE DES DONNEES D’IDENTITE

Inscription et identification préalable pour la fourniture du service
L’utilisation du Site nécessite une inscription et une identification préalable. Vos données nominatives (nom, prénom, adresse postale, e-mail, [compléter]) sont utilisées pour exécuter nos obligations légales résultant de l’inscription à l’Association.
Vous ne fournirez pas de fausses informations nominatives et ne créerez pas de compte pour une autre personne sans son autorisation. Vos coordonnées devront toujours être exactes et à jour.

ARTICLE 8 COLLECTE DES DONNEES D’IDENTIFICATION [Facultatif]

Utilisation de l’identifiant de l’utilisateur pour proposition de mise en relation et offres professionnels
Nous utilisons vos identifiants électroniques pour rechercher des relations présentes par connexion, par adresse mail ou par services. Nous pouvons utiliser vos informations de contact pour permettre à d’autres personnes de trouver votre compte, notamment via des services tiers et des applications clientes. Vous pouvez télécharger votre carnet d’adresses afin que nous soyons en mesure de vous aider à trouver des connaissances sur notre réseau ou pour permettre à d’autres Utilisateurs de notre réseau de vous trouver. Nous pouvons vous proposer des suggestions, à vous et à d’autres Utilisateurs du réseau, à partir des contacts importés de votre carnet d’adresses. Nous sommes susceptibles de travailler en partenariat avec des sociétés qui proposent des offres incitatives. Pour prendre en charge ce type de promotion et d’offre incitative, nous sommes susceptibles de partager votre identifiant électronique.


ARTICLE 9 GEOLOCALISATION

Géolocalisation à des fins de fourniture du service

Nous collectons et traitons vos données de géolocalisation afin de vous fournir nos services. Nous pouvons être amenés à faire usage des données personnelles dans le but de déterminer votre position géographique en temps réel. Conformément à votre droit d’opposition prévu par la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, vous avez la possibilité, à tout moment, de désactiver les fonctions relatives à la géolocalisation.

Géolocalisation à des fins de croisement

Nous collectons et traitons vos données de géolocalisation afin de permettre à nos services d’identifier les points de croisement dans le temps et dans l’espace avec d’autres Utilisateurs du service afin de vous présenter le profil des Utilisateurs croisés. Conformément à votre droit d’opposition prévu par la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, vous avez la possibilité, à tout moment, de désactiver les fonctions relatives à la géolocalisation. Vous reconnaissez alors que le service ne sera plus en mesure de vous présenter de profil des autres Utilisateurs.

Géolocalisation avec mise à disposition des partenaires pour référencement et agrégation (avec opt-in)
Nous pouvons collecter et traiter vos données de géolocalisation avec nos partenaires. Nous nous engageons à anonymiser les données utilisées. Conformément à votre droit d’opposition prévu par la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, vous avez la possibilité, à tout moment, de désactiver les fonctions relatives à la géolocalisation.

ARTICLE 10 COLLECTE DES DONNEES DU TERMINAL

Collecte des données de profilage et des données techniques à des fins de fourniture du service
Certaines des données techniques de votre appareil sont collectées automatiquement par le Site. Ces informations incluent notamment votre adresse IP, fournisseur d’accès à Internet, configuration matérielle, configuration logicielle, type et langue du navigateur… La collecte de ces données est nécessaire à la fourniture des services.

Collecte des données techniques à des fins publicitaires, commerciales et statistiques
Les données techniques de votre appareil sont automatiquement collectées et enregistrées par le Site, à des fins publicitaires, commerciales et statistiques. Ces informations nous aident à personnaliser et à améliorer continuellement votre expérience sur notre Site. Nous ne collectons ni ne conservons aucune donnée nominative (nom, prénom, adresse…) éventuellement attachée à une donnée technique. Les données collectées sont susceptibles d’être revendues à des tiers
.
ARTICLE 11 COOKIES


Durée de conservation des cookies
Conformément aux recommandations de la CNIL, la durée maximale de conservation des cookies est de 13 mois au maximum après leur premier dépôt dans le terminal de l’Utilisateur, tout comme la durée de la validité du consentement de l’Utilisateur à l’utilisation de ces cookies. La durée de vie des cookies n’est pas prolongée à chaque visite. Le consentement de l’Utilisateur devra donc être renouvelé à l’issue de ce délai.
Finalité cookies

Les cookies peuvent être utilisés pour des fins statistiques notamment pour optimiser les services rendus à l’Utilisateur, à partir du traitement des informations concernant la fréquence d’accès, la personnalisation des pages ainsi que les opérations réalisées et les informations consultées.

Vous êtes informé que l’Éditeur est susceptible de déposer des cookies sur votre terminal. Le cookie enregistre des informations relatives à la navigation sur le service (les pages que vous avez consultées, la date et l’heure de la consultation…) que nous pourrons lire lors de vos visites ultérieures.

Droit de l’Utilisateur de refuser les cookies, la désactivation entraînant un fonctionnement dégradé du service
Vous reconnaissez avoir été informé que l’Éditeur peut avoir recours à des cookies, et l’y autorisez. Si vous ne souhaitez pas que des cookies soient utilisés sur votre terminal, la plupart des navigateurs vous permettent de désactiver les cookies en passant par les options de réglage. Toutefois, vous êtes informé que certains services sont susceptibles de ne plus fonctionner correctement.

Association possible des cookies avec des données personnelles pour permettre le fonctionnement du service
L’Éditeur peut être amené à recueillir des informations de navigation via l’utilisation de cookies.

ARTICLE 12 CONSERVATION DES DONNEES TECHNIQUES

Durée de conservation des données techniques
Les données techniques sont conservées pour la durée strictement nécessaire à la réalisation des finalités visées ci-avant.

ARTICLE 13 DELAI DE CONSERVATION DES DONNEES PERSONNELLES [ ET D’ANONYMISATION ]

Conservation des données pendant la durée de la relation contractuelle
Conformément à l’article 6-5° de la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, les données à caractère personnel faisant l’objet d’un traitement ne sont pas conservées au-delà du temps nécessaire à l’exécution des obligations définies lors de la conclusion du contrat ou de la durée prédéfinie de la relation contractuelle
.
Conservation des données anonymisées au-delà de la relation contractuelle / après la suppression du compte 

Nous conservons les données personnelles pour la durée strictement nécessaire à la réalisation des finalités décrites dans la présente Politique. Au-delà de cette durée, elles seront anonymisées et conservées à des fins exclusivement statistiques et ne donneront lieu à aucune exploitation, de quelque nature que ce soit.
Suppression des données après suppression du compte
Des moyens de purge de données sont mis en place afin d’en prévoir la suppression effective dès lors que la durée de conservation ou d’archivage nécessaire à l’accomplissement des finalités déterminées ou imposées est atteinte. Conformément à la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, vous disposez par ailleurs d’un droit de suppression sur vos données que vous pouvez exercer à tout moment en prenant contact avec l’Éditeur.
Suppression des données après 3 ans d’inactivité
Pour des raisons de sécurité, si vous ne vous êtes pas authentifié sur le Site ou que vous n’avez pas eu un comportement actif (clic sur un lien) pendant une période de trois ans, vous recevrez un e-mail vous invitant à vous connecter dans les plus brefs délais, sans quoi vos données seront supprimées de nos bases de données.

ARTICLE 14 SUPPRESSION DU COMPTE

Suppression du compte à la demande

L’Utilisateur a la possibilité de supprimer son Compte à tout moment, par simple demande à l’Éditeur OU par le menu de suppression de Compte présent dans les paramètres du Compte le cas échéant.
Suppression du compte en cas de violation de la Politique de confidentialité
En cas de violation d’une ou de plusieurs dispositions des présentes ou de tout autre document incorporé aux présentes par référence, l’Éditeur se réserve le droit de mettre fin ou restreindre sans aucun avertissement préalable et à sa seule discrétion, votre usage et accès aux services, à votre compte et à tous les Sites.

ARTICLE 15 INDICATIONS EN CAS DE FAILLE DE SECURITE DECELEE PAR L’ÉDITEUR

Information de l’Utilisateur en cas de faille de sécurité
Nous nous engageons à mettre en œuvre toutes les mesures techniques et organisationnelles appropriées grâce à des moyens de sécurisation physiques et logistiques afin de garantir un niveau de sécurité adapté au regard des risques d’accès accidentels, non autorisés ou illégaux, de divulgation, d’altération, de perte ou encore de destruction des données personnelles vous concernant.
Dans l’éventualité où nous prendrions connaissance d’un accès illégal aux données personnelles vous concernant stockées sur nos serveurs ou ceux de nos prestataires, ou d’un accès non autorisé ayant pour conséquence la réalisation des risques identifiés ci-dessus, nous nous engageons à :
” Vous notifier l’incident dans les plus brefs délais si cela répond à un exigence légale ;
” Examiner les causes de l’incident ;
” Prendre les mesures nécessaires dans la limite du raisonnable afin d’amoindrir les effets négatifs et préjudices pouvant résulter dudit incident
Limitation de la responsabilité
En aucun cas les engagements définis au point ci-dessus relatifs à la notification en cas de faille de sécurité ne peuvent être assimilés à une quelconque reconnaissance de faute ou de responsabilité quant à la survenance de l’incident en question.

ARTICLE 16 TRANSFERT DES DONNEES PERSONNELLES A L’ETRANGER

Transfert des données dans des pays avec un niveau de protection équivalent
L’Éditeur s’engage à respecter la réglementation applicable relative aux transferts des données vers des pays étrangers et notamment selon les modalités suivantes :
” L’Éditeur transfère les données personnelles de ses Utilisateurs vers des pays reconnus comme offrant un niveau de protection équivalent.
” L’Éditeur transfère les données personnelles de ses Utilisateurs en dehors des pays reconnus par la CNIL comme ayant un niveau de protection suffisant : L’Éditeur a obtenu une autorisation de la CNIL pour procéder à ce transfert.
Pour connaître la liste de ces pays : CNIL – La protection des données dans le monde

ARTICLE 17 MODIFICATION DE LA POLITIQUE DE CONFIDENTIALITE

En cas de modification des présentes, l’Editeur s’engage à ne pas baisser le niveau de confidentialité de manière substantielle sans l’information préalable des personnes concernées

ARTICLE 18 PORTABILITE DES DONNEES

L’Éditeur s’engage à vous offrir la possibilité de vous faire restituer l’ensemble des données vous concernant sur simple demande. L’Utilisateur se voit ainsi garantir une meilleure maîtrise de ses données, et garde la possibilité de les réutiliser. Ces données devront être fournies dans un format ouvert et aisément réutilisable, directement entre les mains d’un autre responsable de traitement lorsque cela est souhaité et techniquement possible.

ARTICLE 19 DROIT APPLICABLE ET LANGUE

La présente Politique de Confidentialité est régie par le droit français et Suisse. Elles sont rédigées en français. Dans le cas où elles seraient traduites en une ou plusieurs langues, seul le texte français ferait foi en cas de litige. La nullité d’une clause n’entraîne pas la nullité de la Politique de confidentialité. L’inapplication temporaire ou permanente d’une ou plusieurs clauses des présentes par l’Editeur ne saurait valoir renonciation de sa part aux autres clauses des présentes qui continuent à produire leurs effets.

        </p>
=======
>>>>>>> 82befde (first page)
      </section>

      <Footer/>
    </div>
  )
}
