import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import google from "../image/google.svg"
import facebook from "../image/facebook.png"
import signInWith from '../config/service'
import { GoogleAuthProvider, FacebookAuthProvider } from "firebase/auth"
import { useSession, getProviders } from "next-auth/react"
import Footer from '../component/Footer'
import { registerWith } from '../config/service'


export default function Connexion({ providers }:{providers: any}) {
  const { data: session, status } = useSession()
  const GoogleProvider = new GoogleAuthProvider()
  const FacebookProvider = new FacebookAuthProvider()
  // console.log(session)

  if(status === "loading") {
    return <p>Loading...</p>
  }

  // if (status === "unauthenticated") {
  //   return <p>Access Denied</p>
  // }

  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className={styles.login}>
      <form className={styles.part} style={{borderBottom:"solid 1px #D2D2D2"}}>
      <h1 className={styles.h1} style={{fontSize:25}}>Connexion</h1>
        <input type="text" placeholder="Email" />
        <input type="text" placeholder="Mot de passe" />
        <button type="submit" className={styles.action}  style={{animation:"pulse 1sec infite"}}>Connexion</button>
      </form>
      <div className={styles.social} >
        <button 
          style={{backgroundColor:"#437BFF",color:"white"}}
          onClick={() => signInWith(FacebookProvider)}>
          <Image src={facebook} width="25" height="25" /> 
          Connexion
          </button>
        <button 
          style={{backgroundColor:"white",color:"#437BFF", boxShadow:"0px 0px 6px 4px rgba(0,0,0,0.10)"}}
          onClick={() => signInWith(GoogleProvider)}>
          <Image src={google} width="25" height="25" /> 
          Connexion
        </button>
      </div>
      <div>
      {Object.values(providers).map((provider: any) => (
        <div key={provider.name}>
          <button onClick={() => registerWith(provider.id )}>
            Sign in with {provider.name}
          </button>
        </div>
      ))}
    </div>
      </section>
    </div>
    <Footer/>
    </div>
  )
}


export async function getServerSideProps(context: any) {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}
