import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"
import Link from "next/link"
import google from "../image/google.svg"
import facebook from "../image/facebook.png"


export default function Connexion() {

  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className={styles.login}>
      <form className={styles.part} style={{borderBottom:"solid 1px #D2D2D2"}}>
      <h1 className={styles.h1} style={{fontSize:25}}>Connexion</h1>
        <input type="text" placeholder="Email" />
        <input type="text" placeholder="Mot de passe" />
        <button type="submit" className={styles.action}  style={{animation:"pulse 1sec infite"}}>Connexion</button>
      </form>
      <div className={styles.social} >
        <button style={{backgroundColor:"#437BFF",color:"white"}}>
        <Image src={facebook} width="25" height="25" /> 
          Connexion
          </button>
        <button style={{backgroundColor:"white",color:"#437BFF", boxShadow:"0px 0px 6px 4px rgba(0,0,0,0.10)"}}>
        <Image src={google} width="25" height="25" style={{position:"absolute",left:0}} /> 
          Connexion
          </button>
      </div>
      </section>
 
    </div>
    <Footer/>

    </div>
  )
}
