import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../image/whitelogo.png";
import Header from "../component/Header";
import Footer from "../component/Footer";
import { useRouter } from "next/router";

import arrow from "../image/arrow.gif";



export default function contact() {


  return (
    <div className={styles.main2}>
      <Head>
        <title>Conctactez-nous TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header menu="contact"/>
      <section 
          style = {{  background:"rgb(56,135,13",
          background:"linear-gradient(83deg, rgba(56,135,13,1) 0%, rgba(56,135,13,1) 50%, rgba(144,203,6,1) 100%, rgba(211,255,0,1) 100%)",
          width:"100%",        
          paddingTop: 125,
          paddingBottom: 50,
          display:"flex",
          flexDirection:"column",
          alignItems:"center",
          height:"100vh" }}>
          <form className="login animate__animated animate__fadeInUp">
          <h1 style={{ fontSize: 25,color:"green" }}>
              Contactez nous
            </h1>
            <input type="text" placeholder="Nom"/>
            <input type="email" placeholder="Email"/>
            <textarea rows="10" placeholder="Décrire votre message"/>
            <button className="action">Envoyer</button>
          </form>
      </section>
      <Footer />
    </div>
  );
}
