import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import team from "../image/team.jpg";
import Header from "../component/Header";
import Footer from "../component/Footer";


export default function equipe() {


  return (
    <div className={styles.main2}>
      <Head>
        <title>Qui sommes nous ? TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section
className={styles.part}
style={{
  color: " #02558D",
  padding: 0,
  paddingTop:80
}}
>
<section style={{marginTop:50,minHeight:"100vh",
width:"100%",display:"flex",flexDirection:"column",alignItems:"center"}}>
  <div className="team">  <Image style={{width:"50%"}} src={team} alt="team dev"/>
</div>
<div className="team2">
<h2>Une team soudé & passionné </h2>
<p style={{color:"white"}}>Une présentation est un processus qui consiste à communiquer un sujet à un public. Il s'agit généralement d'une démonstration, d'une introduction, d'une conférence ou d'un discours destiné à informer, persuader, inspirer, motiver ou à susciter la bonne volonté <br></br> ou à présenter une nouvelle idée ou un nouveau produit.</p>
</div>
</section>

</section>
      <Footer />
    </div>
  );
}
