import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import logo from "../image/logo.png"
import Header from '../component/Header'
import Footer from "../component/Footer"
import 'animate.css';


export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </Head>
      <Header/>
      <section className={styles.part}>
        <Image src={logo} width="155" height="160" /> 
        <h1 className={styles.h1}>Gagner des lots magique</h1>

        <p>Participer à notre jeux concours afin de recevoir votre lot</p>
       <Link href="/connexion"> 
          <button className={styles.action} style={{margin:25}}>Commencer</button>
        </Link>
      </section>

      <section className={styles.part}>
       <h2 className={styles.h2}>Comment participer ?</h2>
       <ul>
        <li>Vous avez reçu un numéro à 10 chiffres</li>
        <li>Connecter-vous au site</li>
        <li>Rentrer vos numéro dans le champs pour vérifié votre lot</li>
       </ul>
      </section>

      <section className={styles.part} style={{background:"red"}}>
       <h2 className={styles.h2}>Quel sont les lots ?</h2>
       <ul>
          <li>Vous avez reçu un numéro à 10 chiffres</li>
          <li>Connecter-vous au site</li>
          <li>Rentrer vos numéro dans le champs pour vérifié votre lot</li>
       </ul>

      </section>

      <Footer/>
    </div>
  )
}
