import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Thé Bingo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="container">
        <h1>Thé Bingo</h1>
        <p>
        ThéTipTop est une société ayant pour activité la promotion de gammes de thés de très grande qualité avec des mélanges signatures de l’entreprise, des thés détox, des thés blancs, des thés légumes, infusions, etc. L’ensemble des thés sont bios et Handmades.
        </p>
        
        <div className="index-image-liste">
          <div>
            <Image 
              src="/asset/thee.jpg"
              width={300}
              height={300}
            />
          </div>

          <div>
            <p>Pour tout achat d'un montant supperieur à 49 € on vous offre :</p>
            <ul>
              <li>un infuseur à thé</li>
              <li>une boite de 100g d’un thé détox ou d’infusion</li>
              <li>offrent une boite de 100g d’un thé signature</li>
              <li>offrent un coffret découverte d’une valeur de 39€</li>
              <li>offrent un coffret découverte d’une valeur de 69€</li>
            </ul>
          </div>
        </div>
        <p>Attention le jeu concours a lieu pendant 30 jours pendant lesquels 1 500 000 tickets maximums pourront gagner À l’issue du jeu-concours, un tirage au sort sera effectué parmi tous les participants afin de déterminer le gagnant d’un an de thé d’une valeur de 360€.</p>

        <a type="button" className="btn btn-secondary" href='/connexion'>Jouez</a>
      </div>
    </>
  )
}

export default Home
