import React, { useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"
import Link from "next/link"
import google from "../image/google.svg"
import facebook from "../image/facebook.png"
import { useRouter } from 'next/router'


export default function Inscription() {
const [password, setPassword]   = useState(null);
const [confirm, setConfirm]   = useState(null);

  const router = useRouter()
    const goBingo = () => {
      router.push('/bingo')

    }

  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section className={styles.login}>
      <form className={styles.part} style={{borderBottom:"solid 1px #D2D2D2"}}>
      <h1 className={styles.h1} style={{fontSize:25}}>Inscription</h1>
        <input type="text" placeholder="Email" />
        <input type="text" placeholder="Nom prénom" />
        <input type="date" placeholder="Date de naissance" />
        <input type="password" onplaceholder="Mot de passe"     onChange={(e) => {
            setPassword(e.target.value)}}
            value={password} />
        <input type="password" placeholder="Confirmation du mot de passe" 
         onChange={(e) => {setConfirm(e.target.value)}} value={confirm} />
        <button type="button" onClick={goBingo} className={styles.action}  style={{animation:"pulse 1sec infite"}}>Connexion</button>
      </form>
      <div className={styles.social} >
        <button style={{backgroundColor:"#437BFF",color:"white",position:"relative"}}>
        <span  style={{position:"absolute",left:20,bottom:1}}>
             <Image src={facebook} width="16" height="40" objectFit='contain' /> 
          </span>
          S'inscrire
          </button>
        <button style={{backgroundColor:"white",color:"#437BFF", boxShadow:"0px 0px 6px 4px rgba(0,0,0,0.10)"}}>
          <span  style={{position:"absolute",left:8,bottom:1}}>
             <Image src={google} width="40" height="40" /> 
          </span>
          S'inscrire
          </button>
      </div>
      </section>
    <small>Déjà un compte ?<strong style={{color:"#437BFF"}}><Link href="/connexion"> Se connecter</Link>  </strong></small>
    </div>
    <Footer/>

    </div>
  )
}
