import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"
import Count from "../component/Countdown"

export default function Jeux() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className={styles.block} style={{borderBottom:"solid 1px white"}}>
      <div style={{display:"flex",
        flexDirection:"column",
        justifyContent:"center",
        width:"100%",
        padding:15,
        backgroundColor:"#40EFD7" }} >
        <h1 className={styles.h1} style={{color:"white"}}>Grand jeux concour</h1>
        <p style={{fontSize:20,color:"white"}}>Le tirage au sort dans</p>
        < Count />
        
      </div>

        <div style={{display:"flex",
        flexDirection:"column",
        justifyContent:"center",
        padding:15,
        borderTop:"solid 1px white",
        margin:30 }} >
          <h2 className={styles.h2} >Vous avez été sélectionné pour le grand tirage au sort</h2>
          <p>Le 22 avril 2022 un candidat sera sélectionné et bénéficiera de :  </p>
           
      </div>
      </section>

      <Footer/>
    </div>
  )
}
