import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"
import Count from "../component/Countdown"
import tea1 from "../image/tea1.png"
import ClipLoader from "react-spinners/ClockLoader";


export default function Jeux() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section className={styles.block} style={{borderBottom:"solid 1px white"}}>
      <div style={{display:"flex",
        flexDirection:"column",
        justifyContent:"center",
        alignItems:"center",
        width:"100%",
        padding:25,
        backgroundColor:"#40EFD7" }} >
        <h1 className={styles.h1} style={{color:"white"}}>Grand jeux concour</h1>
        <p style={{fontSize:20,color:"white"}}>Le tirage au sort dans</p>
        < Count />
        <ClipLoader color={"white"} loading={true}  size={100} />
      </div>

        <div style={{display:"flex",
        flexDirection:"column",
        justifyContent:"center", }} >
          <h2 className={styles.h2} style={{fontSize:30,padding:20}} >Vous avez été sélectionné pour le grand tirage au sort</h2>
          <p style={{fontSize:22,color:"grey"}}>Le <strong style={{color:"#40EFD7"}}>22 avril 2022</strong> un candidat sera sélectionné et bénéficiera de :  </p>
      </div>
      <p className={"pulse"}  style={{fontSize:18}}>1 an de thé d'une valeur de 360 euros</p>
          <span>
           <Image src={tea1} alt="" width={250} height={220}/>
           </span>
      </section>

      <Footer/>
    </div>
  )
}
