import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../image/whitelogo.png";
import Header from "../component/Header";
import Footer from "../component/Footer";
import { useRouter } from "next/router";
import tea1 from "../image/tea1.png";
import tea2 from "../image/tea2.png";
import tea3 from "../image/tea3.png";
import tea4 from "../image/tea4.png";
import Link from "next/link";

import arrow from "../image/arrow.gif";



export default function lots() {

    const gift = [
        {
          name: "Coffret 32 euros",
          src: tea1,
          descrition:"Le coffret decouverte est composé de 36 sachets de thé avec 6 mélanges de thés différents.",
          href:"/coffret32"
        },
        {
          name: "Coffret 69 euros",
          src: tea1,
          descrition:"Thé matcha pour maigrir ? En tout cas il est nécessaire de l’accompagner avec un régime alimentaire sain afin d’être en bonne santé et pouvoir profiter de ses vertus.",
          href:"/coffret69"
        },
        {
          name: "100g thé signature",
          src: tea2,
          descrition:"super lot",
          href:"/thesignature"
        },
        {
          name: "100g thé detox",
          src: tea3,
          descrition:"L’infusion au pamplemousse, produit détoxifiant, apporte de nombreux bienfaits pour la santé",
          href:"/thedetox"
        },
        {
          name: "Infuseur à thé",
          src: tea4,
          descrition:"super lot",
          href:"/infuseur"
        },
      ];
    


  return (
    <div className={styles.main2}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <section style={{ paddingTop: 125,
      display:"flex",flexWrap:"wrap",
      justifyContent:"center",
      width:"100%", paddingBottom: 50,
        minHeight:"100vh" }}>

        {gift.map((g,i) => (
          <div key={i} className="lotsItems"
        style= { i/2 == Math.round(i/2) ?stylez.dark :stylez.light }
          >
             <h3>{g.name}</h3>
             <Image src={g.src} alt={g.name}/>
             <p>{g.descrition}</p>
             <Link href={g.href}>En savoir plus</Link>
          </div>
            ))}
      </section>
      <Footer />
    </div>
  );
}
const stylez ={

    dark :{
        background :"#0B93F1"
    },

    light:{
        background:"#0B93F1"
    }
}