import React from 'react';
import Head from 'next/head'
import Header from '../component/Header'
import Footer from "../component/Footer"

export default function Politique() {
  return (
    <div className="container">
      <Head>
        <title>Politique de confidentialié</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section className="part">
        <h1 className="h1">Politique de confidentialié</h1>
      </section>

      <Footer/>
    </div>
  )
}
