import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"

export default function Politique() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Politique de confidentialié</title>
        <meta name="description" content="Generated by create next app" />
<<<<<<< HEAD
        <link rel="icon" href="/fav.png" />
=======
        <link rel="icon" href="/favicon.ico" />
>>>>>>> 82befde (first page)
      </Head>
      <Header/>
      <section className={styles.part}>
        <h1 className={styles.h1}>Politique de confidentialié</h1>
      </section>

      <Footer/>
    </div>
  )
}
