import React, { useEffect, useState, useContext } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AllStats from "../component/AllStats";
import Header from "../component/Header";
import Footer from "../component/Footer";
import Users from "../component/Users";
import TicketChecker from "../component/TicketChecker";
import TicketGenerator from "../component/TicketGenerator";
import Sessions from "../component/Sessions";
import { useRouter } from "next/router";
import Cookies from 'js-cookie';
import ApiContext from '../context/apiContext';
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import { getSessions } from "../fonctions/sessions";
import { getGroups } from "../fonctions/groups";


export default function Stats() {
  const context = useContext(ApiContext)
  const router = useRouter();
  const [menu, setMenu] = useState("stats");
  const [session, setSession] = useState({
    name: "",
    start: "",
    end: "",
    limit: 15000,
    id: "",
  });
  const [lots, setLots] = useState([]);
  const [allsessions, setAllSessions] = useState([]);
  const [idSession, setIdSession] = useState("");
  const [width, setWidth] = useState(0);
  
  const updateDimensions = () => {
    setWidth(window.innerWidth);
    Cookies.set("width", width);
  };

  useEffect(() => {
    if(!Cookies.get('authToken') || Cookies.get('role') != "admin"){
      router.push('/connexion')
    }
    getAllSessions();
    getAllLots();
    updateDimensions();
    window.addEventListener("resize", updateDimensions);
    return () => window.removeEventListener("resize", updateDimensions);
  }, [width]);
  
  const getAllSessions = async () => {
    getSessions(context)
    .then((response) => {
      console.log(response,'rep')
      setAllSessions(response);
      setIdSession(response[0]._id);
    })
  };

  const getAllLots = async () => {
    getGroups(context)
    .then((response) => {
      setLots(response);
    })
  };

  const handleChangeSession = (event) => {
    setIdSession(event.target.value);
    setSession(event.target.value);
  };

  const changemenu = (e) => {
    setMenu(e.target.value);
  };

  if(Cookies.get('authToken') && Cookies.get('role') == "admin"){
    return (
      <div className={styles.container}>
        <Head>
          <title>TeaBingo - Jeux concours</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.png" />
        </Head>
        <Header changemenu={changemenu} stylez={stylez} menu={menu} />
  
        <div style={{ display: "flex", width: "100%", background: "green" }}>
          {width > 850 && (
            <div style={stylez.side}>
              <h2 style={{ color: "white", textAlign: "center" }}>Dashboard</h2>
              <button
                value={"stats"}
                style={
                  menu === "stats"
                    ? stylez.sideButtonActive
                    : stylez.sideButtonInactive
                }
                onClick={changemenu}
              >
                Mes stats
              </button>
              <button
                value={"generator"}
                style={
                  menu === "generator"
                    ? stylez.sideButtonActive
                    : stylez.sideButtonInactive
                }
                onClick={changemenu}
              >
                Ticket generator
              </button>
              <button
                value={"ticket"}
                style={
                  menu === "ticket"
                    ? stylez.sideButtonActive
                    : stylez.sideButtonInactive
                }
                onClick={changemenu}
              >
                Ticket checker
              </button>
              <button
                value={"users"}
                style={
                  menu === "users"
                    ? stylez.sideButtonActive
                    : stylez.sideButtonInactive
                }
                onClick={changemenu}
              >
                Listes utilisateurs
              </button>
              <button
                value={"sessions"}
                style={
                  menu === "sessions"
                    ? stylez.sideButtonActive
                    : stylez.sideButtonInactive
                }
                onClick={changemenu}
              >
                {" "}
                Gestions des sessions
              </button>
            </div>
          )}
  
          <div style={width > 850 ? stylez.stat : stylez.fullStat}>
            <div
              style={{
                backgroundColor: "white",
                padding: 25,
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                marginTop: "100px",
              }}
            >
              <h2 className={styles.h2}>Selectionner une session</h2>
              <Select
                labelId="demo-simple-select-label"
                id="demo-simple-select"
                value={idSession}
                label="session"
                onChange={handleChangeSession}
              >
                {allsessions.map((s, index) => (
                  <MenuItem key={index} value={s._id}>
                    {s.name}
                  </MenuItem>
                ))}
              </Select>
            </div>
            {menu === "stats" && <AllStats lots={lots} idSession={idSession} />}
            {menu === "ticket" && <TicketChecker session={idSession} />}
            {menu === "users" && <Users idSession={idSession} />}
            {menu === "generator" && <TicketGenerator session_id={idSession} />}
            {menu === "sessions" && <Sessions idSession={idSession} />}
          </div>
        </div>
        <Footer />
      </div>
    );
  }else{
    return(
      <Box sx={{ width: '100%' }}>
        <LinearProgress />
      </Box>
    )
  }
  
}

const stylez = {
  gain: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    width: "90%",
    maxWidth: 560,
  },
  side: {
    width: "15%",
    paddingTop:100,
    backgroundColor: "white",
    backgroundColor: " #38870D",
    display: "flex",
    flexDirection: "column",
  },
  sideButtonActive: {
    fontSize: 20,
    margin: 5,
    color: "white",
    marginLeft: 0,
    marginRight: 0,
    padding: 10,
    width: "100%",
    border: "none",
    height: 60,
    background: "#96D614",
  },
  sideButtonInactive: {
    fontSize: 20,
    margin: 5,
    color: "#96D614",
    marginLeft: 0,
    marginRight: 0,
    padding: 10,
    width: "100%",
    border: "none",
    height: 60,
    background: "none",
  },
  stat: {
    backgroundColor: "#c7c7c7",
    padding: 25,
    width: "85%",
  },

  fullStat: {
    backgroundColor: "#F1F1F1",
    padding: 25,
    width: "100%",
  },
};
