import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Footer from "../component/Footer"
import StatsLots from '../component/StatsLots'

export default function Stats() {

  const stats  = {
    total:985000,
    totalMax: 1500000, 
  }
 const participation =(stats.total*100)/stats.totalMax
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header/>
      <h1 className={styles.h1}>Mes Stats</h1>
          
        <div  style={stylez.gain2}>
        <h2 style={stylez.h2}>Stats globale</h2>

            <div style={{padding:20,background:"#46E8D1",borderRadius:8,textAlign:"center"}}>
              <p style={{color:"white"}}><strong>{stats.total} </strong>Tickets validés</p>
              <small style={{color:"white",opacity:0.8}}>sur <strong>{stats.totalMax}</strong> tickets</small>
              <p style={{color:"white"}}><strong>{Math.round(participation)}%</strong> taux de participation</p>
            </div>
        </div>
          <div  style={stylez.gain2}>
            <h2 style={stylez.h2}>Stats des lots</h2>
          <StatsLots/>
          </div>
      <Footer/>
    </div>
  )
}

 const stylez = {

  gain : {
    display:"flex",
    flexWrap:"wrap",
    alignItems:"center",
    width:"90%",
    maxWidth:560,
    minHeight:"100vh"
  },
 
  gain2:{
    marginTop:25,
    display:'flex',
    flexDirection:"column"
  },

 h2:{
  color:"#46E8D1",
  textAlign:"center"

 }




}