import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../component/Header";
import Footer from "../component/Footer";
import Ticket from "../component/Ticket";
import { billets } from "../component/Data";
import { DataGrid } from "@mui/x-data-grid";
const columns = [
  { field: "id", headerName: "ID", width: 90 },
  { field: "date", headerName: "date", width: 100, editable: true },
  {
    field: "number",
    headerName: "Number",
    type: "number",
    width: 200,
  },
  {
    field: "lot",
    headerName: "Lot",
    type: "number",
    width: 100,
  },
  {
    field: "email",
    headerName: "Email",
    width: 110,
  },
  ,
];
export default function Tickets() {
  const number = billets.length;
  console.log(billets);
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaBingo - Jeux concours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header />
      <h1 className={styles.h1}>Mes tickets</h1>
      <p style={{ fontSize: 18, color: "grey" }}>
        Vous avez <strong style={{ color: "#41D8C2" }}>{number} </strong>
        {`tickets gagnants`}
      </p>
      <div style={stylez.gain}>
        {billets.length > 0 ? (
          <DataGrid
            rows={billets}
            columns={columns}
            pageSize={15}
            rowsPerPageOptions={[15]}
            checkboxSelection
            disableSelectionOnClick
            experimentalFeatures={{ newEditingApi: true }}
          />
        ) : (
          <p> pas de tickets</p>
        )}
      </div>
      <Footer />
    </div>
  );
}

const stylez = {
  gain: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "red",
    alignItems: "center",
    width: "100vw",
    minHeight: "100vh",
  },
};
