version: "3.8"

networks:
  prod:
     external: true  

volumes:
  frontend_code:

services:
  frontend:
    image: ${IMAGE_BASE}/stable/frontend:${FRONTEND_STABLE_TAG}
    environment:
      - TZ=Europe/Paris
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - frontend_code:/my-project
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - api
    labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`${DOMAIN_BASE}`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - prod