version: "3.8"

networks:
  prod:
     external: true  

#volumes:
#  code:

services:
  frontend:
    image: ${IMAGE_BASE}/stable/frontend:${FRONTEND_STABLE_TAG}
    hostname: dsp-archiwebo21-ct-df-an-cd.fr
    extra_hosts:
      - "api.dsp-archiwebo21-ct-df-an-cd.fr:45.155.170.65" 
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
    volumes:
       - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - api
    labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`${DOMAIN_BASE}`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - prod