version: "3.8"

networks:
  prod:
     external: true  

#volumes:
#  code:

services:
  frontend:
    image: ${IMAGE_BASE}/stable/frontend:${FRONTEND_STABLE_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
      - NEXT_PUBLIC_BASE_URL=http://api:3000
      - NEXT_PUBLIC_GOOGLE_ANALYTICS="G-20KRPHLP3Z"
      - NEXT_PUBLIC_GOOGLE_TAGMANAGER="GTM-KMZCFTF"
      - SITE_URL="https://dsp-archiwebo21-ct-df-an-cd.fr/"
    volumes:
       - /etc/localtime:/etc/localtime:ro
    #   - code:/my-project
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - api
    labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`${DOMAIN_BASE}`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - prod